  name : CICD
  on:
    push:
      branches: ["name"]

    work_dispatch:

  permissions: 
    contents: read
    pages: write
    id-token: write

  concurrency:
    group: "pages"
    cancel-in-process: true

  #Code for continuous integration
  jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          users: actions/checkout@v3
        - name: Setup Pages
          uses: acions/configure-pages@v2
        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ./
            destination: ./_site
        -name: Upload artifact
          uses: actions/upload-pages-artifact@v1

    #Code for continuous deployment
    deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to Github pages
          id: deployment
          uses: action/deploy-pages@v1
          

