name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.x # Specify your Ruby version

      - name: Install Jekyll and Dependencies
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll Site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          cd _site
          git init
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://${{ github.token }}@github.com/${{ github.repository }}.git" master:gh-pages

